"""
This script is used to create a model for classifying if a piece of text is a about movies, film making, or related
topics. The script uses LLMs to generate training data and then trains a classification model on that data.

The model will be used as a guardrail for Theoros, to ensure that the model is only answering questions about movies
and related topics.
"""
import os
import sys
from argparse import ArgumentParser
from concurrent.futures import as_completed
from concurrent.futures.thread import ThreadPoolExecutor
from typing import Literal

import pandas as pd
from pydantic import BaseModel, Field
from pydantic_ai import Agent
from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.litellm import LiteLLMProvider
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from tqdm.auto import tqdm
from tqdm_joblib import tqdm_joblib

model = OpenAIChatModel(
    model_name="deepseek-r1:8b",
    provider=LiteLLMProvider(
        api_key="ollama",
        api_base="http://192.168.4.52:11434/v1"
    )
)

class Example(BaseModel):
    text: str = Field(..., description="A piece of text that is either relevant or irrelevant to movies, film making, or related topics.")
    label: Literal[0, 1] = Field(..., description="The label for the text, where 1 indicates relevant and 0 indicates irrelevant.")

class BatchedExample(BaseModel):
    examples: list[Example] = Field(..., description="A batch of examples generated by the model.")

generating_agent = Agent(
    model=model,
    instructions="""
    Your job is to generate training data for a text classification model that will be used to create relevancy 
    guardrails for Theoros, a movie expert agent. The classification model will be used to determine if a piece of
    text is relevant to movies, film making, or related topics.
    
    The prompt should be either "relevant" or irrelevant" and a number, and you should generate that many examples of 
    text that are either relevant or irrelevant to movies, film making, or related topics.
    """,
    output_type=BatchedExample
)

def generate_training_data(
        label_instruction: Literal["relevant", "irrelevant"],
        batch_size: int = 100,
        num_batches: int = 100,
        num_threads: int = 8
) -> pd.DataFrame:
    """
    Generate training data for the classification model using the generating_agent.

    :param label_instruction: The label instruction for the generating_agent, either "relevant" or "irrelevant".
    :param batch_size: The number of examples to generate in each batch.
    :param num_batches: The number of batches to generate.
    :param num_threads: The number of threads to use for generating the data in parallel.
    :return: A DataFrame containing the generated training data with columns "text" and "label".
    """
    training_data = []
    with ThreadPoolExecutor(max_workers=num_threads) as executor, tqdm(total=num_batches) as pbar:
        futures = []
        for _ in range(num_batches):
            futures.append(executor.submit(
                generating_agent.run_sync,
                f"Generate {batch_size} examples of text that are {label_instruction} to movies, film making, or related topics."
            ))

        for future in as_completed(futures):
            result = future.result()
            if result.response and isinstance(result.output, BatchedExample):
                try:
                    batched_example = result.output
                    for example in batched_example.examples:
                        training_data.append({"text": example.text, "label": 1 if label_instruction == "relevant" else 0})
                except Exception as e:
                    print(f"Error parsing response: {e}")
            pbar.update(1)

    return pd.DataFrame(training_data)

def hyperparameter_tuning(
        training_data: pd.DataFrame,
        estimator: Pipeline,
        num_folds: int = 3,
        num_threads: int = 8
) -> RandomForestClassifier:
    """
    Perform hyperparameter tuning for the Random Forest model using GridSearchCV.

    :param training_data: A DataFrame containing the training data with columns "text" and "label".
    :param num_folds: The number of folds for cross-validation.
    :param num_threads: The number of threads to use for parallel processing.
    :return: The best Random Forest model found during hyperparameter tuning.
    """
    X = training_data["text"]
    y = training_data["label"]

    param_grid = {
        'rf__n_estimators': [100, 200, 300],
        'rf__max_depth': [5, 10, 20, 30],
        'rf__min_samples_split': [2, 5, 10],
        'rf__min_samples_leaf': [1, 2, 4]
    }
    grid_search = GridSearchCV(
        estimator=estimator,
        param_grid=param_grid,
        cv=num_folds,
        n_jobs=num_threads,
        # verbose=2
    )
    num_fits = (len(param_grid['rf__n_estimators']) * len(param_grid['rf__max_depth']) *
                len(param_grid['rf__min_samples_split']) * len(param_grid['rf__min_samples_leaf']) * num_folds)
    with tqdm_joblib(tqdm(desc="Grid Search", total=num_fits)):
        grid_search.fit(X, y)
    print(f"Best parameters found: {grid_search.best_params_}")
    return grid_search.best_estimator_

def train_random_forest_model(
        training_data: pd.DataFrame,
        estimator: Pipeline,
        test_size: float = 0.2,
) -> Pipeline:
    """
    Train a Random Forest model on the provided training data.

    :param training_data: A DataFrame containing the training data with columns "text" and "label".
    :param estimator: The Random Forest estimator to use for training.
    :param test_size: The proportion of the dataset to include in the test split.
    :return: A trained Pipeline containing the TfidfVectorizer and the Random Forest model.
    """
    X = training_data["text"]
    y = training_data["label"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=123)

    estimator.fit(X_train, y_train)

    y_pred = estimator.predict(X_test)
    print(classification_report(y_test, y_pred))

    estimator.fit(X, y)  # Refit on the entire dataset for final model

    return estimator

parser = ArgumentParser(description="Generate training data and train a classification model for movie relevancy.")
parser.add_argument("--batch-size", type=int, default=100,
                    help="Number of examples to generate in each batch.")
parser.add_argument("--num-batches", type=int, default=100,
                    help="Number of batches to generate.")
parser.add_argument("--num-threads", type=int, default=8,
                    help="Number of threads to use for generating the data in parallel.")
parser.add_argument("--prior", type=float, default=0.5,
                    help="Prior probability of a text being relevant to movies, film making, or related topics.")
parser.add_argument("--output-dir", type=str, default="training_data",
                    help="Directory to save the generated training data.")
parser.add_argument("--train-model", action="store_true",
                    help="If set, train the classification model after generating the data.")
parser.add_argument("--tune-hyperparameters", action="store_true",
                    help="If set, perform hyperparameter tuning for the Random Forest model.")
parser.add_argument("--tuning-size", type=float, default=0.2,
                    help="Proportion of the dataset to include in the validation split during hyperparameter tuning.")
parser.add_argument("--test-size", type=float, default=0.2,
                    help="Proportion of the dataset to include in the test split when training the model.")
parser.add_argument("--num-folds", type=int, default=3,
                    help="Number of folds for cross-validation during hyperparameter tuning.")
parser.add_argument("--model-output-path", type=str, default="movie_classifier_model.pkl",
                    help="Path to save the trained classification model.")

def main(args: list[str] | None = None):
    print("Starting training data generation and model training...")
    if args is None:
        args = sys.argv[1:]
    parsed_args = parser.parse_args(args)

    # Generate training data for both relevant and irrelevant examples
    print(f"Generating training data with batch size {parsed_args.batch_size}, "
          f"{parsed_args.num_batches} batches, and prior {parsed_args.prior}...")
    num_relevant = int(parsed_args.batch_size * parsed_args.num_batches * parsed_args.prior)
    num_irrelevant = int(parsed_args.batch_size * parsed_args.num_batches * (1 - parsed_args.prior))
    num_relevant_batches = num_relevant // parsed_args.batch_size
    num_irrelevant_batches = num_irrelevant // parsed_args.batch_size
    relevant_batches = generate_training_data(
        "relevant", parsed_args.batch_size, num_relevant_batches, parsed_args.num_threads
    )
    irrelevant_batches = generate_training_data(
        "irrelevant", parsed_args.batch_size, num_irrelevant_batches, parsed_args.num_threads
    )
    data = pd.concat([relevant_batches, irrelevant_batches], ignore_index=True)
    print(f"Generated {len(data)} training examples. Saving to {parsed_args.output_dir}...")
    if not os.path.exists(parsed_args.output_dir):
        os.makedirs(parsed_args.output_dir)
    data.to_json(os.path.join(parsed_args.output_dir, "training_data.json"), orient="records", lines=True)
    print("Finished generating training data.")

    if parsed_args.train_model:
        print("Training the classification model...")
        _estimator = Pipeline(steps=[
                ('tfidf', TfidfVectorizer()),
                ('rf', RandomForestClassifier(random_state=123))
        ])
        if parsed_args.tune_hyperparameters:
            print("Performing hyperparameter tuning for the Random Forest model...")
            _estimator = hyperparameter_tuning(data, _estimator, parsed_args.num_folds, parsed_args.num_threads)
        print("Training the Random Forest model...")
        model_pipeline = train_random_forest_model(data, _estimator, parsed_args.test_size)
        # Save the trained model
        print(f"Saving the trained model to {parsed_args.model_output_path}...")
        import joblib
        joblib.dump(model_pipeline, parsed_args.model_output_path)
        print(f"Trained model saved to {parsed_args.model_output_path}")

    print("Training data generation and model training completed.")


if __name__ == "__main__":
    main([
        "--batch-size", "100",
        "--num-batches", "100",
        "--num-threads", "8",
        "--prior", "0.5",
        "--output-dir", "training_data",
        "--train-model",
        "--tune-hyperparameters",
        "--tuning-size", "0.2",
        "--test-size", "0.2",
        "--num-folds", "3",
        "--model-output-path", "movie_classifier_model.pkl"
    ])